# Generated by Django 6.1.1 on 2026-09-19 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Session ID')),
                ('project_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Project Path')),
                ('project_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Project Name')),
                ('os', models.CharField(blank=True, default='', max_length=100, verbose_name='Operating System')),
                ('shell', models.CharField(blank=True, default='', max_length=100, verbose_name='Shell')),
                ('system_prompt', models.TextField(blank=True, default='', verbose_name='Generated System Prompt')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_slug', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Session Slug/ID')),
                ('role', models.CharField(default='assistant', max_length=50, verbose_name='Role')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('thinking', models.TextField(blank=True, null=True, verbose_name='Thinking / Reasoning')),
                ('model', models.CharField(blank=True, default='deepseek', max_length=100, verbose_name='Model')),
                ('url', models.CharField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_module.chatsession', verbose_name='Chat Session')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
