# Generated by Django 6.1.1 on 2026-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='permission_mode',
            field=models.CharField(default='bypass_permissions', max_length=50, verbose_name='Permission Execution Mode'),
        ),
    ]
