# Generated by Django 6.0.2 on 2026-10-03 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_module', '0002_chatsession_permission_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='base_ref',
            field=models.CharField(blank=True, default='HEAD', max_length=255, verbose_name='Worktree Base Ref'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='is_worktree_enabled',
            field=models.BooleanField(default=False, verbose_name='Is Worktree Isolation Enabled'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='worktree_branch',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Worktree Branch Name'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='worktree_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Worktree Directory Path'),
        ),
    ]
